# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6uD9Wa05qiONHfnmf9AVnFQCL3mbDCJ
"""

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('WHO COVID-19 cases.csv')

print(df.head())
# Check the actual column names in your DataFrame
print(df.columns)
# Assuming the column name is 'New_cases' based on the DataFrame value in Global variables
cases_by_country = df.groupby('Country')['New_cases'].sum()
top_countries = cases_by_country.sort_values(ascending=False)
print(top_countries)  # Now print top_countries instead of top_10_countries
plt.figure(figsize=(10, 6))
top_countries.head(10).plot(kind='bar')
plt.title('Топ-10 стран по количеству случаев COVID-19')
plt.xlabel('Страна')
plt.ylabel('Количество случаев')
plt.xticks(rotation=45)
plt.show()